FROM node:16-alpine

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . .

ENV REACT_APP_API_URL=http://localhost:4000/
ENV REACT_APP_CURRENCY_API_URL=https://api.apilayer.com/exchangerates_data
ENV REACT_APP_CURRENCY_APIKEY=jr18zv6f9n9fKIsalSTlIlIk9K5qpHZN

RUN npm run build 

CMD [ "npm", "run", "start" ]
EXPOSE 3000
