version: '3.1'

services: 
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clothes_online_store
      PG_DATA: /var/lib/postgresql/data

  nginx:
    depends_on:
      - api
      - client
    restart: always
    ports:
      - 3050:80
    build: ./nginx
      
  # our server
  api: 
   depends_on: 
     - postgres
   volumes:
      - /app/node_modules
      - ./server:/app
   ports:
      - 4000:4000
   env_file: ./server/.env
   build: ./server
   restart: unless-stopped
  
  client: 
    depends_on: 
     - api
    stdin_open: true
    env_file: ./client/.env
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
      
volumes: 
  pgdata:
     