version: '3.1'

services: 
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clothes_online_store
      PG_DATA: /var/lib/postgresql/data

  nginx:
    image: demianeen/online-store-nginx
    build: ./nginx
    depends_on:
      - api
      - client
    restart: always
    ports:
      - 80:80
      
  # our server
  api: 
    container_name: api
    image: demianeen/online-store-api
    build: ./server
    depends_on: 
      - postgres
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 8080:8080
    env_file: ./server/.env
    restart: unless-stopped
  
  client: 
    image: demianeen/online-store-client
    build: ./client
    depends_on: 
      - api
    stdin_open: true
    env_file: ./client/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes: 
      - /app/node_modules
      - ./client:/app
     